### ISSUE TITLE
kubernetes deploy failure

### ISSUE THREAD

**Issue by 18515291426** [jenkinsci/kubernetes-cd-plugin#145]
Starting Kubernetes deployment
Loading configuration: /root/.jenkins/workspace/container-service/container-open-api-test/test.yaml
ERROR: ERROR: Can't construct a java object for tag:yaml.org,2002:io.kubernetes.client.openapi.models.V1Service; exception=Class not found: io.kubernetes.client.openapi.models.V1Service
 in 'reader', line 1, column 1:
    apiVersion: v1
    ^

hudson.remoting.ProxyException: Can't construct a java object for tag:yaml.org,2002:io.kubernetes.client.openapi.models.V1Service; exception=Class not found: io.kubernetes.client.openapi.models.V1Service
 in 'reader', line 1, column 1:
    apiVersion: v1
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:335)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at io.kubernetes.client.util.Yaml$CustomConstructor.constructObject(Yaml.java:337)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:456)
	at io.kubernetes.client.util.Yaml.loadAs(Yaml.java:224)
	at io.kubernetes.client.util.Yaml.modelMapper(Yaml.java:494)
	at io.kubernetes.client.util.Yaml.loadAll(Yaml.java:272)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:236)

**Comment by parlacom** [comment]
Im facing the same issue, please fix it

**Comment by arsamigullin** [comment]
Facing the same. Downgrading both Jackson API to 2.10.3 and Kubernetes-CD plugin to 2.1.0 works but it causes other plugins not to be working. For example, the Kubernetes CLI plugin is not working after downgrading because it requires the Jackson API plugin to be 2.11.3 and higher. 

I had to comment out the part in Jenkinsfile that relies on the Kubernetes CLI plugin

**Comment by GuoDapeng** [comment]
Jenkins2.263.1

```shell
docker run --detach \
 --name jenkins \
 --restart=always \
 -p 8090:8080 \
 -v $PWD/jenkins_home:/var/jenkins_home \
 -v /var/run/docker.sock:/var/run/docker.sock \
 jenkinsci/blueocean
```

![截屏2020-12-09 上午12 16 59](https://user-images.githubusercontent.com/7477750/101509822-243ff580-39b4-11eb-89d3-f87ef0b5768d.png)


我在研究如何卸载 Jackson 尝试安装 2.10.3

**Comment by maps90** [comment]
facing the same issue.. any update on this yet ?
