### ISSUE TITLE
Plugin is not available on jenkins 

### ISSUE THREAD

**Issue by hamzanasir443** [jenkinsci/kubernetes-cd-plugin#164]
### Describe your use-case which is not covered by existing documentation.

Hi 

Could you please suggest the alternate method for which the plugin is used now for deployment ? 

Regards: Hamza

**Comment by jumping** [comment]
https://www.jenkins.io/security/advisory/2022-08-23/#SECURITY-2448 any alternative solutions？

**Comment by hamzanasir443** [comment]
> https://www.jenkins.io/security/advisory/2022-08-23/#SECURITY-2448 any alternative solutions？

You can download the older version of plugin and manually installed on jenkins

**Comment by emoxam** [comment]
2.3.1 from other place doesnt' work, it's dont like apiv1 in deployment.yaml
It's bad the project is abandoned

**Comment by Trojaner** [comment]
An updated version is available here:
https://github.com/byo-software/kubernetes-cd-plugin

Note: none of the security advisories have been addressed.

**Comment by emoxam** [comment]
> An updated version is available here: https://github.com/byo-software/kubernetes-cd-plugin
> 
> Note: none of the security advisories have been addressed.

Thanks, i will give it a try!

**Comment by emoxam** [comment]
I've got a problem, tabs at source java code doesn't supported ?

```Starting Kubernetes deployment
Loading configuration: /var/lib/jenkins/workspace/demo-app/Dockerfile
No resource loaded from: /var/lib/jenkins/workspace/demo-app/Dockerfile
Loading configuration: /var/lib/jenkins/workspace/demo-app/pom.xml
No resource loaded from: /var/lib/jenkins/workspace/demo-app/pom.xml
Loading configuration: /var/lib/jenkins/workspace/demo-app/src/main/java/ru/integris/demo/DemoApplication.java
ERROR: ERROR: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 9, column 1:
    	public static void main(String[ ... 
    ^

hudson.remoting.ProxyException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 9, column 1:
    	public static void main(String[ ... 
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:453)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:273)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:279)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
```

String 9 is
```	public static void main(String[] args) {```
And it's really begins with TAB

**Comment by emoxam** [comment]
Config file setting should be **/*.yaml
Pardon, and thanks. All working

**Comment by sitaorg2022** [comment]
> > https://www.jenkins.io/security/advisory/2022-08-23/#SECURITY-2448 any alternative solutions？
> 
> You can download the older version of plugin and manually installed on jenkins

Are you able to download the old version ?

**Comment by sitaorg2022** [comment]
> https://www.jenkins.io/security/advisory/2022-08-23/#SECURITY-2448 any alternative solutions？

Did you find the Solution

**Comment by Evengard** [comment]
Unfortunately, after digging into it, the work needed to fix that is more than just updating the deps version. Some Kubernetes schemas got deprecated and removed from the java client. Now to update the version (which will get rid of that CVE) one need to update all the referenced wrappers. And that's not that easy.

**Comment by emoxam** [comment]
> Unfortunately, after digging into it, the work needed to fix that is more than just updating the deps version. Some Kubernetes schemas got deprecated and removed from the java client. Now to update the version (which will get rid of that CVE) one need to update all the referenced wrappers. And that's not that easy.

One guy fixed it, but it's not support ingresses, so i use kubectl apply -f and then i think i get do all the stuf this way, without any jenkins plugins..)

**Comment by MarkEWaite** [comment]
The plugin is up for adoption.  If your organization needs this plugin, then you should persuade your organization to let you adopt the plugin, fix the security issue, modernize the plugin, and release a new version with the fix.
