### ISSUE TITLE
Operation: [get] for kind: [Secret] with name: [ ] in namespace: [default] failed.

### ISSUE THREAD

**Issue by viktorg2** [jenkinsci/kubernetes-cd-plugin#21]
Hello

I have a problem that I can't figure out. I'm running your plugin within jenkins declarative pipeline. Jenkins server has kubectl installed as well as access to the kubernetes cluster. I can run get/create/delete cmds from jenkins server with no problems. I do get this error for some reason. I even manually created and specified "docker-hub-registry-created-manually" but it doesn't exists. Any idea?

my stage looks like this:
##
 stage('Deploying Docker Image') {
                          steps {
                            script {
                             kubernetesDeploy(
                                credentialsType: 'KubeConfig',
                                kubeConfig: [path: '/var/lib/jenkins/workspace/.kube/'],
                                configs: 'applications-deployment.yml',
                                enableConfigSubstitution: true,
                                secretNamespace: '',
                                secretName: 'docker-hub-registry-created-manually',
                                dockerCredentials: [
                                    [credentialsId: 'hub_credentials_id_here', server: 'https://registry.hub.docker.com'],
                                ],
                             )
                            }
                          }
                        }
##
Note:
I did also try using just [credentialsId: 'hub_credentials_id_here' ] and different combinations but still getting same error. Maybe someone can shed some light for me. Thanks in advance.

Here is the full error output from jenkins job:
##
Starting Kubernetes deployment
Prepare Docker container registry secrets with name: docker-hub-registry-created-manually
ERROR: ERROR: Operation: [get]  for kind: [Secret]  with name: [docker-hub-registry-created-manually]  in namespace: [default]  failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Secret]  with name: [docker-hub-registry-created-manually]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:228)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:184)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$SecretUpdater.getCurrentResource(KubernetesClientWrapper.java:736)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$SecretUpdater.getCurrentResource(KubernetesClientWrapper.java:725)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$ResourceUpdater.createOrApply(KubernetesClientWrapper.java:319)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.createOrReplaceSecrets(KubernetesClientWrapper.java:193)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:90)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:66)
	at hudson.FilePath.act(FilePath.java:1096)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:66)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:787)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:217)
	... 25 more
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: Kubernetes deployment ended with HasError
Finished: FAILURE

**Comment by ArieShout** [comment]
Currently the `kubeConfig` parameter only accepts a path relative to the workspace of the project. The workspace directory for a given project will be some path like `/var/lib/jenkins/workspace/<project-name>`. Consider if you have a project `k8s-test`, you can place the kubeconfig file to path `/var/lib/jenkins/workspace/k8s-test/kubeconfig`, and use the relative path `kubeconfig` for the `kubeConfig` parameter.

This is not user friendly and was also raised in #18 . An enhancement has been implemented in #20 . And will be available in the next release.

**Comment by viktorg2** [comment]
Thanks for ArieShout.
I figured out my problem. Believe it or not but once I specified full path to kubernetes config file (had to copy it over to the jenkins box) everything started working like a charm! Ability to pass variable within yml file is just awesome. Thanks for great plugin! This is how my config looks like now.

kubernetesDeploy(
                                credentialsType: 'KubeConfig',
                                kubeConfig: [path: '/var/lib/jenkins/workspace/.kube/config'],
                                configs: 'mypods-deployment.yml', 
                                dockerCredentials: [
                                      [credentialsId: 'my_registry_creds_id'],
                                ],

**Comment by ArieShout** [comment]
This will be enhanced in #20 in the next release. With that change, we only need to prepare the kubeconfig in the Jenkins master and it will be available to the slaves without manually copy.
