### ISSUE TITLE
Null Pointer Exception on deploying a cronjob 

### ISSUE THREAD

**Issue by CSNWEB** [jenkinsci/kubernetes-cd-plugin#27]
Hello,

when I try to deploy a cronjob I get the following error: 

```
Loading configuration: /home/jenkins/workspace/services_jenkins-test-XO46LEN76A4SRY5UHHB7TIJEC6LPJOOXXGO4K2VO2S7KI32P6WFQ/.kube/services-cron.yml
ERROR: ERROR: null
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:286)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:278)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:65)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:134)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:102)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:66)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-10-40-0-0.eu-central-1.compute.internal/10.40.0.0:55726
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at hudson.FilePath.act(FilePath.java:1093)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:66)
		at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
		at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
		at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Kubernetes deployment ended with HasError
```

Not sure if they are meant to be working, the README only lists jobs, would be great if they would be supported though! Thanks for your help in advance. The yaml looks like this:

```YAML
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: services-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: env
              secret:
                secretName: env
                items:
                - key: env_file
                  path: .env
          containers:
          - name: services-worker
            image: "kiron/services:${BRANCH_NAME}-${BUILD_ID}"
            args:
            - /bin/bash
            - -c
            - /services/cron-startup.sh
            volumeMounts:
              - name: env
                mountPath: /var/www/html/services/internal-october/.env
                subPath: .env
                readOnly: true
              - name: env
                mountPath: /var/www/html/services/api/.env
                subPath: .env
                readOnly: true
          restartPolicy: OnFailure

```

Sidenotes: Applying the yaml with kubectl directly works and the containers and volume mounts are used in a deployment and also work fine.

**Comment by ArieShout** [comment]
`CronJob` is not supported by the kubernetes-client. [Here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler) is a handler list which deal with the CRUD of each type of Kubernetes resources. Currently, `CronJob` is not handled so we don't have its support. We will watch for the list update.

**Comment by andrii29** [comment]
Hi.
Do you planning to add support for cron jobs?

**Comment by dabeck** [comment]
CronJob support was added on 12 Jul. When does this feature come into the plugin?

[Link](https://github.com/fabric8io/kubernetes-client/commit/4216df1e0f4c790b112dca8adb75a782e71b75b3#diff-1f6e155fd768d8098f72258e0dcc855c)
