### ISSUE TITLE
Operation: [get]  for kind: [Deployment]  with name: [demo-client-deployment]  in namespace: [default]  failed.

### ISSUE THREAD

**Issue by aholen** [jenkinsci/kubernetes-cd-plugin#33]
Hi, I have similar problems like mentioned in https://github.com/jenkinsci/kubernetes-cd-plugin/issues/21 but probably a different issue.

The kubernetes api/controller is on the same subnet as the jenkins server. Using kubectl on the jenkins-server, using the same kubeconfig-file as configured in the credentials for the job(Using _"From a file on the Jenkins master"_ ), I can successfully connect to the cluster and communicate with the cluster. (apply and get pods)
I've also tried to start up jenkins with -Djava.net.preferIPv4Stack=true - didn't help, other than slightly different stacktrace.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
error: yaml: line 9: mapping values are not allowed in this context
```

Jenkins version: jenkins-2.11
Kubernetes Continuous Deploy Plugin version: 0.2.1

```
 <builders>
    <com.microsoft.jenkins.kubernetes.KubernetesDeploy plugin="kubernetes-cd@0.2.1">
      <context>
        <kubeconfigId>kube-dev</kubeconfigId>
        <credentialsType>KubeConfig</credentialsType>
        <ssh>
          <sshServer></sshServer>
          <sshCredentialsId>*</sshCredentialsId>
        </ssh>
        <kubeConfig>
          <path></path>
        </kubeConfig>
        <textCredentials>
          <serverUrl>https://</serverUrl>
          <certificateAuthorityData></certificateAuthorityData>
          <clientCertificateData></clientCertificateData>
          <clientKeyData></clientKeyData>
        </textCredentials>
        <configs>solution/demo/*.yaml</configs>
        <enableConfigSubstitution>true</enableConfigSubstitution>
        <secretName>regcred</secretName>
      </context>
    </com.microsoft.jenkins.kubernetes.KubernetesDeploy>
  </builders>
```

```
ERROR: ERROR: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Deployment]  with name: [demo-client-deployment]  in namespace: [default]  failed.
hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Deployment]  with name: [demo-client-deployment]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:206)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:162)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$DeploymentUpdater.getCurrentResource(KubernetesClientWrapper.java:390)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$DeploymentUpdater.getCurrentResource(KubernetesClientWrapper.java:378)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$ResourceUpdater.createOrApply(KubernetesClientWrapper.java:344)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:143)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:169)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:123)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.FilePath.act(FilePath.java:1096)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:67)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:46)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.remoting.ProxyException: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:770)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:195)
	... 26 more
```

**Comment by ArieShout** [comment]
This is likely to be caused by invalid configuration of the Kubeconfig credentials. You can verify if the stored credential is working following the guides at [Kubeconfig Binding](https://github.com/jenkinsci/kubernetes-cd-plugin#kubeconfig-binding):

```groovy
withCredentials([kubeconfigContent(credentialsId: 'acs-ssh-folder', variable: 'KUBECONFIG_CONTENT')]) {
    sh '''cat "$KUBECONFIG_CONTENT" >kubeconfig && kubectl version --kubeconfig kubeconfig && rm kubeconfig'''
}
```

Besides in your `kubectl version` invocation, there is an error

> error: yaml: line 9: mapping values are not allowed in this context

which may be a possible cause.

**Comment by aholen** [comment]
Hi, thanks for the reply and tips, I dug into this.

In your example, is the variable $KUBECONFIG_CONTENT expected to contain the path/filename of the kubeconfig-file, or the actual contents? 
If the latter, the command should be echo, not cat:

```
withCredentials([kubeconfigContent(credentialsId: 'acs-ssh-folder', variable: 'KUBECONFIG_CONTENT')]) {
    sh '''echo "$KUBECONFIG_CONTENT" >kubeconfig && kubectl version --kubeconfig kubeconfig && rm kubeconfig'''
}
```
I'm currently using manual job creation for this, so please bear with me, but using your examples, I could verify the credentials with this "Execute shell"

```
echo "$KUBECONFIG_CONTENT" >kubeconfig && kubectl version --kubeconfig kubeconfig
kubectl get pods -n demo --kubeconfig kubeconfig
``

**Comment by aholen** [comment]
Finally got it working now. The problem was that my kubeconfig-file only had client-certificate-data,  not token.
So I extracted my token:
```console
$ kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')
```
...and added that to my kubelet-user in my kubeconfig-file, so:
```console
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://kubernetes.example:443
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: ""
current-context: ""
kind: Config
preferences:
  colors: true
users:
- name: kubelet
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED
````

Closing this, but this should maybe be documented

**Comment by kazihuo** [comment]
Hi, My cluster is created by kubeadm. I use jenkins with pipeline for kubernetes and make the same mistake as you.  I checkout the kubeconfig-file , finding the user is different with you and not token also. looking:
`# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.1.65.131:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
`
How can I solve this problem?   Thank you . 
I am  Beginner of k8s and I need the Operation steps and commands..
I hope you can help me, Thank you .

**Comment by timur206** [comment]
I have a similar problem. How to resolve this ? Maybe someone have a some guide ?
