### ISSUE TITLE
Support for certificate and issuer kind

### ISSUE THREAD

**Issue by viktorg2** [jenkinsci/kubernetes-cd-plugin#34]
Hello

Can you please add support for certmanager (https://cert-manager.readthedocs.io/en/latest/index.html) kinds below?
kind: Issuer
kind: Certificate

I'm getting below error:

Starting Kubernetes deployment
Prepare Docker container registry secrets with name: acs-plugin--82v49qlpso
Created Secret: name: acs-plugin--82v49qlpso
Inject environment variable KUBERNETES_SECRET_NAME=acs-plugin--82v49qlpso
Loading configuration: /var/lib/jenkins/workspace/clientservice_pipeline_dev-LPTE35OK5G75U3THHWBN6X4V5PQRJ5B6DD6GUTNCQN4M36O5K7PA/clientservice-certificate.yml
ERROR: ERROR: An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:131)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:93)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:184)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:170)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:101)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.load(DefaultKubernetesClient.java:101)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:119)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:102)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:66)
	at hudson.FilePath.act(FilePath.java:1096)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:66)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:Certificate
 at [Source: java.io.BufferedInputStream@17e8699a; line: 25, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:982)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:56)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:129)
	... 26 more

**Comment by ArieShout** [comment]
We rely on the resource handlers defined in [the list](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ResourceHandler) to handle resource CRUD. It's not trivial to support CertManager and Issuer at the moment.
