### ISSUE TITLE
xxx is invalid: type: Invalid value: "kubernetes.io/dockercfg": field is immutable,

### ISSUE THREAD

**Issue by kaybinwong** [jenkinsci/kubernetes-cd-plugin#55]
```
失败控制台输出

Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on Jenkins in /data/jenkins/jobs/test-k8s-pipeline/workspace
[Pipeline] {
[Pipeline] kubernetesDeploy
Starting Kubernetes deployment
Prepare Docker container registry secrets with name: registry-harbor
ERROR: ERROR: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://192.168.64.75:6443/api/v1/namespaces/inf-dev/secrets/registry-harbor. Message: Secret "registry-harbor" is invalid: type: Invalid value: "kubernetes.io/dockercfg": field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=type, message=Invalid value: "kubernetes.io/dockercfg": field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Secret, name=registry-harbor, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Secret "registry-harbor" is invalid: type: Invalid value: "kubernetes.io/dockercfg": field is immutable, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://192.168.64.75:6443/api/v1/namespaces/inf-dev/secrets/registry-harbor. Message: Secret "registry-harbor" is invalid: type: Invalid value: "kubernetes.io/dockercfg": field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=type, message=Invalid value: "kubernetes.io/dockercfg": field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Secret, name=registry-harbor, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Secret "registry-harbor" is invalid: type: Invalid value: "kubernetes.io/dockercfg": field is immutable, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:280)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:766)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:156)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:152)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:26)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:5)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:163)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:60)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:50)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:26)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$SecretUpdater.applyResource(KubernetesClientWrapper.java:829)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$SecretUpdater.applyResource(KubernetesClientWrapper.java:804)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$ResourceUpdater.createOrApply(KubernetesClientWrapper.java:362)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.createOrReplaceSecrets(KubernetesClientWrapper.java:226)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:156)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:122)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:105)
	at hudson.FilePath.act(FilePath.java:1159)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:67)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:46)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Kubernetes deployment ended with HasError
Finished: FAILURE
```

secret `registry-harbor` on namespace `inf-dev` which was created by kubectl
```
kubectl create secret docker-registry registry-harbor --docker-server=registry.xxx.cc --docker-username=inf --docker-password=1*1y8HC$ --docker-email=inf@xx.cc -n inf-dev
```

script pipeline

```
node {
    kubernetesDeploy(kubeconfigId: 'dev-inf-k8s-config',               // REQUIRED
        configs: 'kubernetes/*.yaml', // REQUIRED
        enableConfigSubstitution: false,
        secretNamespace: 'inf-dev',
        secretName: 'registry-harbor',
        dockerCredentials: [
            [credentialsId: 'inf-harbor', url: "https://registry.xx.cc"]
        ]
    )
}
```

is this  a bug?

**Comment by kaybinwong** [comment]
there are 2 questions, any one can help me ?
1. why i need to configure the registry secret duplicated? one in dockerCredentials, the other in secretNamespace and secretName?
2. is better to ref secret in the deployment.yaml, but not int the pipeline?

**Comment by kocsistemsahne** [comment]
Hi
Is this solved? And how?

**Comment by jastabile** [comment]
@kaybinwong did you fix this
